import React from "react";
import { useParams } from "react-router-dom";
import { Card, Button, Container, Col, Row, Table } from "react-bootstrap";
import CardPlayerDetail from "../../components/CardPlayerDetail/CardPlayerDetail";
import "./Player.css";
const player = {
  url: "Asuna",
  name: "Asuna",
  realName: "Peter Mazuryk",
  team: "100_Thieves",
  imageUrl: "https://songmotor.com/wp-content/uploads/2019/11/placeholder.png",
  country: ["United States", "Ukraine"],
  born: "2003-07-26",
  mainAgent: ["Jett", "Reyna", "Chamber"],
  gamingGear: {
    mouse: { brand: "Razer", name: "Razer Deathadder V2" },
    mousepad: { brand: "Artisan", name: "Artisan FX Zero Soft" },
    monitor: { brand: "Zowie_gear", name: "ZOWIE XL2546K" },
    keyboard: { brand: "Corsair", name: "CORSAIR K70 RGB" },
    headset: { brand: "Hyperx", name: "HyperX Cloud II" },
  },
  matches: [
    {
      player: "Asuna",
      date: "2022-03-15",
      tournament: "Proving Grounds $20k - Spring 2022",
      map: "Haven",
      kill: "10",
      death: "18",
      assist: "5",
      team1: "100 Thieves",
      team2: "SoaR",
      agents1: ["Jett", "Breach", "Chamber", "Sova", "Omen"],
      agents2: ["Sova", "Jett", "Omen", "Breach", "Killjoy"],
      score: "10:13",
    },
    {
      player: "Asuna",
      date: "2022-03-15",
      tournament: "Proving Grounds $20k - Spring 2022",
      map: "Breeze",
      kill: "16",
      death: "15",
      assist: "3",
      team1: "100 Thieves",
      team2: "SoaR",
      agents1: ["Reyna", "KAY/O", "Chamber", "Sova", "Viper"],
      agents2: ["Sova", "Jett", "Viper", "KAY/O", "Chamber"],
      score: "7:13",
    },
    {
      player: "Asuna",
      date: "2022-03-15",
      tournament: "Proving Grounds $20k - Spring 2022",
      map: "Icebox",
      kill: "20",
      death: "16",
      assist: "5",
      team1: "100 Thieves",
      team2: "Teal Seam",
      agents1: ["Chamber", "KAY/O", "Omen", "Sova", "Viper"],
      agents2: ["KAY/O", "Viper", "Chamber", "Sova", "Jett"],
      score: "13:9",
    },
    {
      player: "Asuna",
      date: "2022-03-14",
      tournament: "Proving Grounds $20k - Spring 2022",
      map: "Ascent",
      kill: "18",
      death: "14",
      assist: "3",
      team1: "100 Thieves",
      team2: "Teal Seam",
      agents1: ["Jett", "KAY/O", "Sova", "Killjoy", "Brimstone"],
      agents2: ["KAY/O", "Omen", "Killjoy", "Sova", "Jett"],
      score: "13:7",
    },
    {
      player: "Asuna",
      date: "2022-03-12",
      tournament: "VCT 2022: North America Stage 1 Challengers",
      map: "Haven",
      kill: "18",
      death: "21",
      assist: "1",
      team1: "100 Thieves",
      team2: "Evil Geniuses",
      agents1: ["Jett", "Omen", "Breach", "Chamber", "Sova"],
      agents2: ["Chamber", "Jett", "Breach", "Brimstone", "Sova"],
      score: "14:12",
    },
    {
      player: "Asuna",
      date: "2022-03-12",
      tournament: "VCT 2022: North America Stage 1 Challengers",
      map: "Breeze",
      kill: "19",
      death: "21",
      assist: "5",
      team1: "100 Thieves",
      team2: "Evil Geniuses",
      agents1: ["Reyna", "Viper", "KAY/O", "Chamber", "Sova"],
      agents2: ["Jett", "Chamber", "Sova", "Viper", "KAY/O"],
      score: "13:11",
    },
    {
      player: "Asuna",
      date: "2022-03-06",
      tournament: "VCT 2022: North America Stage 1 Challengers",
      map: "Split",
      kill: "14",
      death: "13",
      assist: "6",
      team1: "100 Thieves",
      team2: "XSET",
      agents1: ["Raze", "Astra", "Breach", "Chamber", "Viper"],
      agents2: ["Viper", "Skye", "Chamber", "Astra", "Raze"],
      score: "4:13",
    },
    {
      player: "Asuna",
      date: "2022-03-06",
      tournament: "VCT 2022: North America Stage 1 Challengers",
      map: "Fracture",
      kill: "20",
      death: "15",
      assist: "13",
      team1: "100 Thieves",
      team2: "XSET",
      agents1: ["Raze", "Astra", "Breach", "Chamber", "Viper"],
      agents2: ["Viper", "Breach", "Chamber", "Astra", "Raze"],
      score: "13:9",
    },
    {
      player: "Asuna",
      date: "2022-03-06",
      tournament: "VCT 2022: North America Stage 1 Challengers",
      map: "Breeze",
      kill: "16",
      death: "14",
      assist: "2",
      team1: "100 Thieves",
      team2: "XSET",
      agents1: ["Jett", "Chamber", "KAY/O", "Sova", "Viper"],
      agents2: ["Viper", "Sova", "Jett", "Astra", "KAY/O"],
      score: "8:13",
    },
    {
      player: "Asuna",
      date: "2022-02-27",
      tournament: "VCT 2022: North America Stage 1 Challengers",
      map: "Breeze",
      kill: "21",
      death: "19",
      assist: "3",
      team1: "100 Thieves",
      team2: "Luminosity Gaming",
      agents1: ["Jett", "Chamber", "KAY/O", "Sova", "Viper"],
      agents2: ["Sova", "Jett", "KAY/O", "Cypher", "Viper"],
      score: "12:14",
    },
    {
      player: "Asuna",
      date: "2022-02-27",
      tournament: "VCT 2022: North America Stage 1 Challengers",
      map: "Fracture",
      kill: "12",
      death: "17",
      assist: "5",
      team1: "100 Thieves",
      team2: "Luminosity Gaming",
      agents1: ["Raze", "Astra", "Breach", "Chamber", "Viper"],
      agents2: ["Breach", "Chamber", "Raze", "Viper", "Astra"],
      score: "13:9",
    },
    {
      player: "Asuna",
      date: "2022-02-27",
      tournament: "VCT 2022: North America Stage 1 Challengers",
      map: "Split",
      kill: "15",
      death: "17",
      assist: "3",
      team1: "100 Thieves",
      team2: "Luminosity Gaming",
      agents1: ["Raze", "Astra", "Skye", "Chamber", "Viper"],
      agents2: ["Skye", "Sage", "Raze", "Cypher", "Astra"],
      score: "9:13",
    },
    {
      player: "Asuna",
      date: "2022-02-25",
      tournament: "Knights Arena Monthly Gauntlet 2022: February",
      map: "Ascent",
      kill: "12",
      death: "21",
      assist: "7",
      team1: "100 Thieves",
      team2: "TSM",
      agents1: ["Jett", "KAY/O", "Sova", "Killjoy", "Astra"],
      agents2: ["Jett", "Sova", "KAY/O", "Astra", "Chamber"],
      score: "10:13",
    },
    {
      player: "Asuna",
      date: "2022-02-25",
      tournament: "Knights Arena Monthly Gauntlet 2022: February",
      map: "Split",
      kill: "21",
      death: "18",
      assist: "7",
      team1: "100 Thieves",
      team2: "TSM",
      agents1: ["Raze", "Skye", "Chamber", "Viper", "Astra"],
      agents2: ["Raze", "Viper", "Breach", "Astra", "Chamber"],
      score: "14:12",
    },
    {
      player: "Asuna",
      date: "2022-02-25",
      tournament: "Knights Arena Monthly Gauntlet 2022: February",
      map: "Icebox",
      kill: "19",
      death: "24",
      assist: "4",
      team1: "100 Thieves",
      team2: "TSM",
      agents1: ["Jett", "Reyna", "Sage", "Sova", "Viper"],
      agents2: ["Jett", "Sova", "Sage", "Viper", "Chamber"],
      score: "13:15",
    },
    {
      player: "Asuna",
      date: "2022-02-25",
      tournament: "Knights Arena Monthly Gauntlet 2022: February",
      map: "Haven",
      kill: "13",
      death: "12",
      assist: "4",
      team1: "100 Thieves",
      team2: "Andbox",
      agents1: ["Jett", "Skye", "Sova", "Killjoy", "Astra"],
      agents2: ["Sova", "Astra", "Jett", "Chamber", "Breach"],
      score: "13:3",
    },
    {
      player: "Asuna",
      date: "2022-02-25",
      tournament: "Knights Arena Monthly Gauntlet 2022: February",
      map: "Split",
      kill: "11",
      death: "14",
      assist: "3",
      team1: "100 Thieves",
      team2: "Andbox",
      agents1: ["Raze", "Skye", "Chamber", "Viper", "Astra"],
      agents2: ["Raze", "Astra", "Chamber", "Viper", "Breach"],
      score: "4:13",
    },
    {
      player: "Asuna",
      date: "2022-02-25",
      tournament: "Knights Arena Monthly Gauntlet 2022: February",
      map: "Breeze",
      kill: "18",
      death: "15",
      assist: "4",
      team1: "100 Thieves",
      team2: "Andbox",
      agents1: ["Jett", "KAY/O", "Sova", "Chamber", "Viper"],
      agents2: ["Sova", "Astra", "Chamber", "Viper", "KAY/O"],
      score: "13:8",
    },
    {
      player: "Asuna",
      date: "2022-02-24",
      tournament: "Knights Arena Monthly Gauntlet 2022: February",
      map: "Ascent",
      kill: "27",
      death: "14",
      assist: "2",
      team1: "100 Thieves",
      team2: "TSM Academy",
      agents1: ["Jett", "KAY/O", "Sova", "Killjoy", "Astra"],
      agents2: ["Sova", "Astra", "Jett", "Killjoy", "KAY/O"],
      score: "13:9",
    },
    {
      player: "Asuna",
      date: "2022-02-24",
      tournament: "Knights Arena Monthly Gauntlet 2022: February",
      map: "Fracture",
      kill: "14",
      death: "15",
      assist: "8",
      team1: "100 Thieves",
      team2: "TSM Academy",
      agents1: ["Raze", "Breach", "Chamber", "Viper", "Astra"],
      agents2: ["Breach", "Astra", "Neon", "Chamber", "Skye"],
      score: "13:6",
    },
    {
      player: "Asuna",
      date: "2022-02-24",
      tournament: "Knights Arena Monthly Gauntlet 2022: February",
      map: "Split",
      kill: "14",
      death: "12",
      assist: "7",
      team1: "100 Thieves",
      team2: "ex-Limit",
      agents1: ["Raze", "Skye", "Chamber", "Viper", "Astra"],
      agents2: ["Viper", "KAY/O", "Chamber", "Raze", "Astra"],
      score: "13:5",
    },
    {
      player: "Asuna",
      date: "2022-02-24",
      tournament: "Knights Arena Monthly Gauntlet 2022: February",
      map: "Haven",
      kill: "21",
      death: "4",
      assist: "3",
      team1: "100 Thieves",
      team2: "ex-Limit",
      agents1: ["Jett", "Skye", "Sova", "Killjoy", "Astra"],
      agents2: ["Chamber", "Jett", "Astra", "Skye", "Sova"],
      score: "13:0",
    },
    {
      player: "Asuna",
      date: "2022-02-21",
      tournament: "VCT 2022: North America Stage 1 Challengers",
      map: "Ascent",
      kill: "3",
      death: "13",
      assist: "3",
      team1: "100 Thieves",
      team2: "The Guard",
      agents1: ["Chamber", "Cypher", "Astra", "Skye", "Sova"],
      agents2: ["Sage", "Killjoy", "Jett", "Sova", "Astra"],
      score: "0:13",
    },
    {
      player: "Asuna",
      date: "2022-02-21",
      tournament: "VCT 2022: North America Stage 1 Challengers",
      map: "Split",
      kill: "14",
      death: "12",
      assist: "8",
      team1: "100 Thieves",
      team2: "The Guard",
      agents1: ["Raze", "Cypher", "Astra", "Skye", "Viper"],
      agents2: ["Skye", "Chamber", "Raze", "Viper", "Astra"],
      score: "13:6",
    },
    {
      player: "Asuna",
      date: "2022-02-20",
      tournament: "VCT 2022: North America Stage 1 Challengers",
      map: "Haven",
      kill: "23",
      death: "20",
      assist: "8",
      team1: "100 Thieves",
      team2: "The Guard",
      agents1: ["Jett", "Cypher", "Astra", "Skye", "Sova"],
      agents2: ["Skye", "Killjoy", "Jett", "Sova", "Astra"],
      score: "12:14",
    },
    {
      player: "Asuna",
      date: "2022-02-11",
      tournament: "VCT 2022: North America Stage 1 Challengers",
      map: "Breeze",
      kill: "20",
      death: "13",
      assist: "2",
      team1: "100 Thieves",
      team2: "Cloud9",
      agents1: ["Jett", "Cypher", "Viper", "Skye", "Sova"],
      agents2: ["Jett", "Chamber", "Viper", "KAY/O", "Sova"],
      score: "6:13",
    },
    {
      player: "Asuna",
      date: "2022-02-11",
      tournament: "VCT 2022: North America Stage 1 Challengers",
      map: "Split",
      kill: "18",
      death: "17",
      assist: "3",
      team1: "100 Thieves",
      team2: "Cloud9",
      agents1: ["Raze", "Astra", "Cypher", "Skye", "Viper"],
      agents2: ["Chamber", "Killjoy", "Astra", "Raze", "Breach"],
      score: "10:13",
    },
    {
      player: "Asuna",
      date: "2021-11-14",
      tournament: "Community Gaming Valorant Elite Showdown",
      map: "Ascent",
      kill: "19",
      death: "21",
      assist: "8",
      team1: "Actually Homeless",
      team2: "Evil Geniuses",
      agents1: ["Skye", "Killjoy", "Astra", "Reyna", "Sova"],
      agents2: ["Jett", "Astra", "Sova", "Killjoy", "Skye"],
      score: "12:14",
    },
    {
      player: "Asuna",
      date: "2021-11-13",
      tournament: "Community Gaming Valorant Elite Showdown",
      map: "Icebox",
      kill: "10",
      death: "13",
      assist: "10",
      team1: "Actually Homeless",
      team2: "Evil Geniuses",
      agents1: ["Sova", "Killjoy", "Viper", "Reyna", "Jett"],
      agents2: ["Jett", "Viper", "Sova", "Sage", "Reyna"],
      score: "3:13",
    },
    {
      player: "Asuna",
      date: "2021-11-13",
      tournament: "Community Gaming Valorant Elite Showdown",
      map: "Split",
      kill: "17",
      death: "12",
      assist: "12",
      team1: "Actually Homeless",
      team2: "Evil Geniuses",
      agents1: ["Sage", "Killjoy", "Astra", "Reyna", "Jett"],
      agents2: ["Jett", "Astra", "Sage", "Viper", "Skye"],
      score: "13:8",
    },
    {
      player: "Asuna",
      date: "2021-11-10",
      tournament: "NSG: Winter Championship - Open 4",
      map: "Icebox",
      kill: "7",
      death: "15",
      assist: "12",
      team1: "Actually Homeless",
      team2: "TSM Academy",
      agents1: ["Sova", "Killjoy", "Viper", "Reyna", "Jett"],
      agents2: ["Jett", "Sova", "Viper", "Killjoy", "Sage"],
      score: "9:13",
    },
    {
      player: "Asuna",
      date: "2021-11-10",
      tournament: "NSG: Winter Championship - Open 4",
      map: "Bind",
      kill: "9",
      death: "18",
      assist: "5",
      team1: "Actually Homeless",
      team2: "TSM Academy",
      agents1: ["Astra", "Sage", "Viper", "Yoru", "Sova"],
      agents2: ["Jett", "Sova", "Astra", "Viper", "Skye"],
      score: "6:13",
    },
    {
      player: "Asuna",
      date: "2021-11-09",
      tournament: "NSG: Winter Championship - Open 4",
      map: "Ascent",
      kill: "25",
      death: "15",
      assist: "5",
      team1: "Actually Homeless",
      team2: "Elysium",
      agents1: ["Skye", "Killjoy", "Astra", "Reyna", "Sova"],
      agents2: ["Sova", "Killjoy", "Astra", "Jett", "KAY/O"],
      score: "13:11",
    },
    {
      player: "Asuna",
      date: "2021-11-09",
      tournament: "NSG: Winter Championship - Open 4",
      map: "Haven",
      kill: "15",
      death: "11",
      assist: "7",
      team1: "Actually Homeless",
      team2: "Elysium",
      agents1: ["Skye", "Cypher", "Astra", "Reyna", "Sova"],
      agents2: ["KAY/O", "Cypher", "Astra", "Jett", "Skye"],
      score: "13:5",
    },
    {
      player: "Asuna",
      date: "2021-11-09",
      tournament: "NSG: Winter Championship - Open 4",
      map: "Haven",
      kill: "16",
      death: "7",
      assist: "5",
      team1: "Actually Homeless",
      team2: "Radiance",
      agents1: ["Skye", "Cypher", "Astra", "Reyna", "Sova"],
      agents2: ["Jett", "Reyna", "Sova", "Astra", "Cypher"],
      score: "13:1",
    },
    {
      player: "Asuna",
      date: "2021-11-09",
      tournament: "NSG: Winter Championship - Open 4",
      map: "Breeze",
      kill: "25",
      death: "9",
      assist: "2",
      team1: "Actually Homeless",
      team2: "Radiance",
      agents1: ["Skye", "Killjoy", "Viper", "Reyna", "Sova"],
      agents2: ["Jett", "Skye", "Sova", "Astra", "Viper"],
      score: "13:6",
    },
    {
      player: "Asuna",
      date: "2021-10-31",
      tournament: "VCT 2021: North America Last Chance Qualifier",
      map: "Breeze",
      kill: "17",
      death: "14",
      assist: "6",
      team1: "100 Thieves",
      team2: "Cloud9 Blue",
      agents1: ["Reyna", "Viper", "Skye", "Sova", "Jett"],
      agents2: ["Jett", "Cypher", "KAY/O", "Sova", "Viper"],
      score: "5:13",
    },
    {
      player: "Asuna",
      date: "2021-10-30",
      tournament: "VCT 2021: North America Last Chance Qualifier",
      map: "Haven",
      kill: "15",
      death: "16",
      assist: "6",
      team1: "100 Thieves",
      team2: "Cloud9 Blue",
      agents1: ["Jett", "Astra", "Skye", "Sova", "Cypher"],
      agents2: ["Jett", "Killjoy", "Raze", "Sova", "Astra"],
      score: "9:13",
    },
    {
      player: "Asuna",
      date: "2021-10-30",
      tournament: "VCT 2021: North America Last Chance Qualifier",
      map: "Icebox",
      kill: "30",
      death: "21",
      assist: "5",
      team1: "100 Thieves",
      team2: "Cloud9 Blue",
      agents1: ["Reyna", "Viper", "Sage", "Sova", "Jett"],
      agents2: ["Jett", "Sage", "Reyna", "Sova", "Viper"],
      score: "14:12",
    },
    {
      player: "Asuna",
      date: "2021-10-30",
      tournament: "VCT 2021: North America Last Chance Qualifier",
      map: "Haven",
      kill: "17",
      death: "19",
      assist: "6",
      team1: "100 Thieves",
      team2: "Rise",
      agents1: ["Jett", "Astra", "Skye", "Sova", "Cypher"],
      agents2: ["Sova", "Phoenix", "Cypher", "Jett", "Astra"],
      score: "11:13",
    },
    {
      player: "Asuna",
      date: "2021-10-30",
      tournament: "VCT 2021: North America Last Chance Qualifier",
      map: "Ascent",
      kill: "21",
      death: "15",
      assist: "1",
      team1: "100 Thieves",
      team2: "Rise",
      agents1: ["Reyna", "Astra", "Skye", "Sova", "Jett"],
      agents2: ["Sova", "Skye", "Killjoy", "Jett", "Astra"],
      score: "13:10",
    },
    {
      player: "Asuna",
      date: "2021-10-30",
      tournament: "VCT 2021: North America Last Chance Qualifier",
      map: "Breeze",
      kill: "21",
      death: "21",
      assist: "4",
      team1: "100 Thieves",
      team2: "Rise",
      agents1: ["Reyna", "Viper", "Skye", "Sova", "Jett"],
      agents2: ["Sova", "Skye", "Killjoy", "Jett", "Viper"],
      score: "11:13",
    },
    {
      player: "Asuna",
      date: "2021-10-13",
      tournament: "VCT 2021: North America Last Chance Qualifier",
      map: "Ascent",
      kill: "20",
      death: "15",
      assist: "5",
      team1: "100 Thieves",
      team2: "XSET",
      agents1: ["Reyna", "Astra", "Skye", "Sova", "Jett"],
      agents2: ["Killjoy", "Sova", "Astra", "Jett", "Skye"],
      score: "13:9",
    },
    {
      player: "Asuna",
      date: "2021-10-13",
      tournament: "VCT 2021: North America Last Chance Qualifier",
      map: "Breeze",
      kill: "27",
      death: "12",
      assist: "2",
      team1: "100 Thieves",
      team2: "XSET",
      agents1: ["Reyna", "Viper", "Skye", "Sova", "Jett"],
      agents2: ["Killjoy", "Sova", "Viper", "Jett", "Skye"],
      score: "13:8",
    },
    {
      player: "Asuna",
      date: "2021-10-13",
      tournament: "VCT 2021: North America Last Chance Qualifier",
      map: "Split",
      kill: "8",
      death: "19",
      assist: "4",
      team1: "100 Thieves",
      team2: "XSET",
      agents1: ["Raze", "Astra", "Skye", "Viper", "Jett"],
      agents2: ["Viper", "Sage", "Astra", "Skye", "Raze"],
      score: "9:13",
    },
    {
      player: "Asuna",
      date: "2021-10-12",
      tournament: "VCT 2021: North America Last Chance Qualifier",
      map: "Icebox",
      kill: "14",
      death: "10",
      assist: "5",
      team1: "100 Thieves",
      team2: "Gen.G Esports",
      agents1: ["Reyna", "Viper", "Sage", "Sova", "Jett"],
      agents2: ["Omen", "Viper", "Jett", "Sage", "Sova"],
      score: "13:4",
    },
    {
      player: "Asuna",
      date: "2021-10-12",
      tournament: "VCT 2021: North America Last Chance Qualifier",
      map: "Split",
      kill: "18",
      death: "14",
      assist: "10",
      team1: "100 Thieves",
      team2: "Gen.G Esports",
      agents1: ["Raze", "Astra", "Skye", "Viper", "Jett"],
      agents2: ["Astra", "Sage", "Raze", "Reyna", "Cypher"],
      score: "13:8",
    },
    {
      player: "Asuna",
      date: "2021-10-12",
      tournament: "VCT 2021: North America Last Chance Qualifier",
      map: "Breeze",
      kill: "23",
      death: "15",
      assist: "8",
      team1: "100 Thieves",
      team2: "Gen.G Esports",
      agents1: ["Reyna", "Viper", "Skye", "Sova", "Jett"],
      agents2: ["Brimstone", "Viper", "Jett", "Skye", "Cypher"],
      score: "10:13",
    },
    {
      player: "Asuna",
      date: "2021-09-18",
      tournament: "VCT 2021: Stage 3 Masters - Berlin",
      map: "Ascent",
      kill: "19",
      death: "17",
      assist: "5",
      team1: "100 Thieves",
      team2: "Team Envy",
      agents1: ["Jett", "Skye", "Sova", "Astra", "Killjoy"],
      agents2: ["Sova", "Killjoy", "Astra", "Skye", "Jett"],
      score: "8:13",
    },
    {
      player: "Asuna",
      date: "2021-09-18",
      tournament: "VCT 2021: Stage 3 Masters - Berlin",
      map: "Haven",
      kill: "9",
      death: "16",
      assist: "5",
      team1: "100 Thieves",
      team2: "Team Envy",
      agents1: ["Jett", "Skye", "Sova", "Astra", "Killjoy"],
      agents2: ["Sova", "Killjoy", "Astra", "Skye", "Jett"],
      score: "5:13",
    },
    {
      player: "Asuna",
      date: "2021-09-17",
      tournament: "VCT 2021: Stage 3 Masters - Berlin",
      map: "Breeze",
      kill: "21",
      death: "18",
      assist: "5",
      team1: "100 Thieves",
      team2: "Acend",
      agents1: ["Reyna", "Skye", "Sova", "Jett", "Viper"],
      agents2: ["Viper", "Jett", "Cypher", "Skye", "Sova"],
      score: "14:12",
    },
    {
      player: "Asuna",
      date: "2021-09-17",
      tournament: "VCT 2021: Stage 3 Masters - Berlin",
      map: "Haven",
      kill: "21",
      death: "15",
      assist: "5",
      team1: "100 Thieves",
      team2: "Acend",
      agents1: ["Jett", "Skye", "Sova", "Astra", "Killjoy"],
      agents2: ["Astra", "Jett", "Cypher", "Skye", "Phoenix"],
      score: "13:8",
    },
    {
      player: "Asuna",
      date: "2021-09-17",
      tournament: "VCT 2021: Stage 3 Masters - Berlin",
      map: "Ascent",
      kill: "8",
      death: "16",
      assist: "5",
      team1: "100 Thieves",
      team2: "Acend",
      agents1: ["Jett", "Skye", "Sova", "Astra", "Killjoy"],
      agents2: ["Astra", "Jett", "Killjoy", "Sage", "Sova"],
      score: "9:13",
    },
    {
      player: "Asuna",
      date: "2021-09-12",
      tournament: "VCT 2021: Stage 3 Masters - Berlin",
      map: "Split",
      kill: "23",
      death: "21",
      assist: "6",
      team1: "100 Thieves",
      team2: "Gambit Esports",
      agents1: ["Jett", "Skye", "Viper", "Astra", "KAY/O"],
      agents2: ["Viper", "Jett", "Cypher", "Astra", "Skye"],
      score: "13:10",
    },
    {
      player: "Asuna",
      date: "2021-09-12",
      tournament: "VCT 2021: Stage 3 Masters - Berlin",
      map: "Icebox",
      kill: "23",
      death: "19",
      assist: "4",
      team1: "100 Thieves",
      team2: "Gambit Esports",
      agents1: ["Reyna", "Omen", "Sova", "Viper", "Killjoy"],
      agents2: ["Sova", "Jett", "Viper", "Sage", "Reyna"],
      score: "13:11",
    },
    {
      player: "Asuna",
      date: "2021-09-12",
      tournament: "VCT 2021: Stage 3 Masters - Berlin",
      map: "Ascent",
      kill: "13",
      death: "15",
      assist: "0",
      team1: "100 Thieves",
      team2: "Gambit Esports",
      agents1: ["Jett", "Skye", "Sova", "Omen", "KAY/O"],
      agents2: ["Sova", "Jett", "Cypher", "Astra", "Skye"],
      score: "5:13",
    },
    {
      player: "Asuna",
      date: "2021-09-10",
      tournament: "VCT 2021: Stage 3 Masters - Berlin",
      map: "Icebox",
      kill: "22",
      death: "12",
      assist: "2",
      team1: "100 Thieves",
      team2: "Havan Liberty",
      agents1: ["Reyna", "Omen", "Sova", "Viper", "Killjoy"],
      agents2: ["Sova", "Jett", "Viper", "Sage", "Reyna"],
      score: "13:6",
    },
    {
      player: "Asuna",
      date: "2021-09-10",
      tournament: "VCT 2021: Stage 3 Masters - Berlin",
      map: "Ascent",
      kill: "12",
      death: "13",
      assist: "2",
      team1: "100 Thieves",
      team2: "Havan Liberty",
      agents1: ["Jett", "Skye", "Sova", "Omen", "KAY/O"],
      agents2: ["Sova", "Jett", "Skye", "Astra", "Breach"],
      score: "13:3",
    },
    {
      player: "Asuna",
      date: "2021-08-15",
      tournament: "VCT 2021: North America Stage 3 Challengers Playoffs",
      map: "Split",
      kill: "15",
      death: "12",
      assist: "2",
      team1: "100 Thieves",
      team2: "Sentinels",
      agents1: ["Jett", "Skye", "Viper", "Astra", "KAY/O"],
      agents2: ["Cypher", "Jett", "Sage", "Reyna", "Astra"],
      score: "5:13",
    },
    {
      player: "Asuna",
      date: "2021-08-15",
      tournament: "VCT 2021: North America Stage 3 Challengers Playoffs",
      map: "Haven",
      kill: "12",
      death: "15",
      assist: "4",
      team1: "100 Thieves",
      team2: "Sentinels",
      agents1: ["Jett", "Skye", "Sova", "Omen", "KAY/O"],
      agents2: ["Killjoy", "Sova", "Phoenix", "Jett", "Astra"],
      score: "6:13",
    },
    {
      player: "Asuna",
      date: "2021-08-15",
      tournament: "VCT 2021: North America Stage 3 Challengers Playoffs",
      map: "Breeze",
      kill: "19",
      death: "20",
      assist: "5",
      team1: "100 Thieves",
      team2: "Sentinels",
      agents1: ["Reyna", "Skye", "Viper", "Omen", "Cypher"],
      agents2: ["Killjoy", "Sova", "Skye", "Jett", "Viper"],
      score: "13:11",
    },
    {
      player: "Asuna",
      date: "2021-08-15",
      tournament: "VCT 2021: North America Stage 3 Challengers Playoffs",
      map: "Bind",
      kill: "13",
      death: "21",
      assist: "7",
      team1: "100 Thieves",
      team2: "Sentinels",
      agents1: ["Raze", "Skye", "Breach", "Astra", "Jett"],
      agents2: ["Viper", "Sova", "Raze", "Reyna", "Astra"],
      score: "11:13",
    },
    {
      player: "Asuna",
      date: "2021-08-14",
      tournament: "VCT 2021: North America Stage 3 Challengers Playoffs",
      map: "Split",
      kill: "16",
      death: "12",
      assist: "4",
      team1: "100 Thieves",
      team2: "Team Envy",
      agents1: ["Jett", "Skye", "Viper", "Astra", "KAY/O"],
      agents2: ["Cypher", "Viper", "Astra", "Skye", "Reyna"],
      score: "13:5",
    },
    {
      player: "Asuna",
      date: "2021-08-14",
      tournament: "VCT 2021: North America Stage 3 Challengers Playoffs",
      map: "Icebox",
      kill: "16",
      death: "17",
      assist: "4",
      team1: "100 Thieves",
      team2: "Team Envy",
      agents1: ["Reyna", "Omen", "Sova", "Viper", "Killjoy"],
      agents2: ["Sova", "Killjoy", "Viper", "Raze", "Jett"],
      score: "8:13",
    },
    {
      player: "Asuna",
      date: "2021-08-14",
      tournament: "VCT 2021: North America Stage 3 Challengers Playoffs",
      map: "Ascent",
      kill: "21",
      death: "17",
      assist: "4",
      team1: "100 Thieves",
      team2: "Team Envy",
      agents1: ["Jett", "Skye", "Sova", "Omen", "KAY/O"],
      agents2: ["Sova", "Killjoy", "Astra", "Raze", "Jett"],
      score: "13:10",
    },
    {
      player: "Asuna",
      date: "2021-08-14",
      tournament: "VCT 2021: North America Stage 3 Challengers Playoffs",
      map: "Breeze",
      kill: "18",
      death: "17",
      assist: "4",
      team1: "100 Thieves",
      team2: "Team Envy",
      agents1: ["Reyna", "Skye", "Viper", "Omen", "Cypher"],
      agents2: ["Sova", "Killjoy", "Viper", "Skye", "Jett"],
      score: "13:10",
    },
    {
      player: "Asuna",
      date: "2021-08-14",
      tournament: "VCT 2021: North America Stage 3 Challengers Playoffs",
      map: "Haven",
      kill: "14",
      death: "14",
      assist: "4",
      team1: "100 Thieves",
      team2: "Team Envy",
      agents1: ["Jett", "Skye", "Sova", "Omen", "KAY/O"],
      agents2: ["Sova", "Killjoy", "Astra", "Skye", "Jett"],
      score: "5:13",
    },
    {
      player: "Asuna",
      date: "2021-08-13",
      tournament: "VCT 2021: North America Stage 3 Challengers Playoffs",
      map: "Haven",
      kill: "8",
      death: "18",
      assist: "3",
      team1: "100 Thieves",
      team2: "Sentinels",
      agents1: ["Jett", "Skye", "Sova", "Omen", "KAY/O"],
      agents2: ["Killjoy", "Sova", "Phoenix", "Jett", "Astra"],
      score: "8:13",
    },
    {
      player: "Asuna",
      date: "2021-08-13",
      tournament: "VCT 2021: North America Stage 3 Challengers Playoffs",
      map: "Split",
      kill: "10",
      death: "12",
      assist: "1",
      team1: "100 Thieves",
      team2: "Sentinels",
      agents1: ["Jett", "Skye", "Viper", "Astra", "KAY/O"],
      agents2: ["Killjoy", "Jett", "Sage", "Reyna", "Astra"],
      score: "2:13",
    },
    {
      player: "Asuna",
      date: "2021-08-12",
      tournament: "VCT 2021: North America Stage 3 Challengers Playoffs",
      map: "Ascent",
      kill: "26",
      death: "19",
      assist: "3",
      team1: "100 Thieves",
      team2: "XSET",
      agents1: ["Jett", "Skye", "Sova", "Omen", "KAY/O"],
      agents2: ["Killjoy", "Sova", "Astra", "Jett", "Skye"],
      score: "13:11",
    },
    {
      player: "Asuna",
      date: "2021-08-12",
      tournament: "VCT 2021: North America Stage 3 Challengers Playoffs",
      map: "Haven",
      kill: "22",
      death: "18",
      assist: "5",
      team1: "100 Thieves",
      team2: "XSET",
      agents1: ["Jett", "Skye", "Sova", "Omen", "KAY/O"],
      agents2: ["Cypher", "Sova", "Astra", "Jett", "Skye"],
      score: "13:11",
    },
    {
      player: "Asuna",
      date: "2021-08-11",
      tournament: "VCT 2021: North America Stage 3 Challengers Playoffs",
      map: "Breeze",
      kill: "28",
      death: "13",
      assist: "9",
      team1: "100 Thieves",
      team2: "FaZe Clan",
      agents1: ["Reyna", "Skye", "Viper", "Omen", "Cypher"],
      agents2: ["Jett", "Killjoy", "Yoru", "Sova", "Viper"],
      score: "13:9",
    },
    {
      player: "Asuna",
      date: "2021-08-11",
      tournament: "VCT 2021: North America Stage 3 Challengers Playoffs",
      map: "Haven",
      kill: "16",
      death: "15",
      assist: "3",
      team1: "100 Thieves",
      team2: "FaZe Clan",
      agents1: ["Jett", "Skye", "Sova", "Omen", "KAY/O"],
      agents2: ["Jett", "Cypher", "Phoenix", "Sova", "Astra"],
      score: "13:6",
    },
    {
      player: "Asuna",
      date: "2021-07-11",
      tournament: "VCT 2021: North America Stage 3 Challengers 1",
      map: "Breeze",
      kill: "15",
      death: "19",
      assist: "5",
      team1: "100 Thieves",
      team2: "Sentinels",
      agents1: ["Reyna", "Sage", "Viper", "Omen", "Skye"],
      agents2: ["Killjoy", "Sova", "Skye", "Jett", "Viper"],
      score: "8:13",
    },
    {
      player: "Asuna",
      date: "2021-07-11",
      tournament: "VCT 2021: North America Stage 3 Challengers 1",
      map: "Haven",
      kill: "29",
      death: "19",
      assist: "4",
      team1: "100 Thieves",
      team2: "Sentinels",
      agents1: ["Jett", "Skye", "Sova", "Omen", "Cypher"],
      agents2: ["Cypher", "Sova", "Phoenix", "Jett", "Omen"],
      score: "13:15",
    },
    {
      player: "Asuna",
      date: "2021-07-10",
      tournament: "VCT 2021: North America Stage 3 Challengers 1",
      map: "Ascent",
      kill: "10",
      death: "18",
      assist: "6",
      team1: "100 Thieves",
      team2: "XSET",
      agents1: ["Phoenix", "Sage", "Sova", "Omen", "Killjoy"],
      agents2: ["Killjoy", "Sova", "Astra", "Jett", "Skye"],
      score: "10:13",
    },
    {
      player: "Asuna",
      date: "2021-07-10",
      tournament: "VCT 2021: North America Stage 3 Challengers 1",
      map: "Icebox",
      kill: "23",
      death: "11",
      assist: "4",
      team1: "100 Thieves",
      team2: "XSET",
      agents1: ["Reyna", "Omen", "Sova", "Viper", "Killjoy"],
      agents2: ["Viper", "Sova", "Sage", "Jett", "Raze"],
      score: "13:4",
    },
    {
      player: "Asuna",
      date: "2021-07-10",
      tournament: "VCT 2021: North America Stage 3 Challengers 1",
      map: "Haven",
      kill: "19",
      death: "20",
      assist: "6",
      team1: "100 Thieves",
      team2: "XSET",
      agents1: ["Jett", "Skye", "Sova", "Omen", "Cypher"],
      agents2: ["Cypher", "Sova", "Astra", "Jett", "Skye"],
      score: "12:14",
    },
    {
      player: "Asuna",
      date: "2021-07-09",
      tournament: "VCT 2021: North America Stage 3 Challengers 1",
      map: "Icebox",
      kill: "11",
      death: "16",
      assist: "2",
      team1: "100 Thieves",
      team2: "Team Envy",
      agents1: ["Reyna", "Omen", "Sova", "Viper", "Killjoy"],
      agents2: ["Sova", "Killjoy", "Viper", "Jett", "Reyna"],
      score: "13:7",
    },
    {
      player: "Asuna",
      date: "2021-07-09",
      tournament: "VCT 2021: North America Stage 3 Challengers 1",
      map: "Haven",
      kill: "17",
      death: "13",
      assist: "3",
      team1: "100 Thieves",
      team2: "Team Envy",
      agents1: ["Jett", "Skye", "Sova", "Omen", "Cypher"],
      agents2: ["Sova", "Killjoy", "Omen", "Jett", "Phoenix"],
      score: "13:9",
    },
    {
      player: "Asuna",
      date: "2021-07-08",
      tournament: "VCT 2021: North America Stage 3 Challengers 1",
      map: "Haven",
      kill: "11",
      death: "10",
      assist: "7",
      team1: "100 Thieves",
      team2: "Version1",
      agents1: ["Jett", "Skye", "Sova", "Omen", "Cypher"],
      agents2: ["Sova", "Jett", "Cypher", "Omen", "Viper"],
      score: "13:5",
    },
    {
      player: "Asuna",
      date: "2021-07-08",
      tournament: "VCT 2021: North America Stage 3 Challengers 1",
      map: "Icebox",
      kill: "48",
      death: "24",
      assist: "6",
      team1: "100 Thieves",
      team2: "Version1",
      agents1: ["Reyna", "Omen", "Sova", "Viper", "Killjoy"],
      agents2: ["Sova", "Jett", "Reyna", "Sage", "Viper"],
      score: "19:17",
    },
    {
      player: "Asuna",
      date: "2021-07-04",
      tournament:
        "VCT 2021: North America Stage 3 Challengers 1 - Open Qualifier",
      map: "Ascent",
      kill: "21",
      death: "13",
      assist: "3",
      team1: "100 Thieves",
      team2: "Noble",
      agents1: ["Phoenix", "Sage", "Sova", "Omen", "Killjoy"],
      agents2: ["Raze", "Omen", "Sova", "Killjoy", "Sage"],
      score: "13:8",
    },
    {
      player: "Asuna",
      date: "2021-07-03",
      tournament:
        "VCT 2021: North America Stage 3 Challengers 1 - Open Qualifier",
      map: "Icebox",
      kill: "20",
      death: "19",
      assist: "6",
      team1: "100 Thieves",
      team2: "Noble",
      agents1: ["Reyna", "Omen", "Sova", "Viper", "Killjoy"],
      agents2: ["Jett", "Omen", "Sova", "Viper", "Sage"],
      score: "9:13",
    },
    {
      player: "Asuna",
      date: "2021-07-03",
      tournament:
        "VCT 2021: North America Stage 3 Challengers 1 - Open Qualifier",
      map: "Haven",
      kill: "19",
      death: "16",
      assist: "3",
      team1: "100 Thieves",
      team2: "Noble",
      agents1: ["Jett", "Skye", "Sova", "Omen", "Cypher"],
      agents2: ["Raze", "Astra", "Sova", "Cypher", "Skye"],
      score: "13:9",
    },
    {
      player: "Asuna",
      date: "2021-07-02",
      tournament:
        "VCT 2021: North America Stage 3 Challengers 1 - Open Qualifier",
      map: "Haven",
      kill: "18",
      death: "13",
      assist: "3",
      team1: "100 Thieves",
      team2: "SoaR",
      agents1: ["Jett", "Skye", "Sova", "Omen", "Cypher"],
      agents2: ["Phoenix", "Sova", "Cypher", "Jett", "Omen"],
      score: "13:6",
    },
    {
      player: "Asuna",
      date: "2021-07-02",
      tournament:
        "VCT 2021: North America Stage 3 Challengers 1 - Open Qualifier",
      map: "Ascent",
      kill: "9",
      death: "17",
      assist: "8",
      team1: "100 Thieves",
      team2: "SoaR",
      agents1: ["Phoenix", "Sage", "Sova", "Omen", "Killjoy"],
      agents2: ["Phoenix", "Sova", "Cypher", "Jett", "Omen"],
      score: "13:7",
    },
    {
      player: "Asuna",
      date: "2021-07-02",
      tournament:
        "VCT 2021: North America Stage 3 Challengers 1 - Open Qualifier",
      map: "Icebox",
      kill: "23",
      death: "21",
      assist: "4",
      team1: "100 Thieves",
      team2: "SoaR",
      agents1: ["Reyna", "Omen", "Sova", "Viper", "Killjoy"],
      agents2: ["Raze", "Sova", "Sage", "Jett", "Viper"],
      score: "11:13",
    },
    {
      player: "Asuna",
      date: "2021-06-11",
      tournament: "BFC Smeag Cup #1",
      map: "Breeze",
      kill: "5",
      death: "15",
      assist: "5",
      team1: "Team vanity",
      team2: "Team tarik",
      agents1: ["Reyna", "Jett", "Sova", "Skye", "Viper"],
      agents2: ["Sage", "Sova", "Viper", "Jett", "Reyna"],
      score: "2:13",
    },
    {
      player: "Asuna",
      date: "2021-05-01",
      tournament: "VCT 2021: North America Stage 2 Challengers Finals",
      map: "Haven",
      kill: "23",
      death: "21",
      assist: "8",
      team1: "100 Thieves",
      team2: "Team Envy",
      agents1: ["Phoenix", "Skye", "Sova", "Omen", "Cypher"],
      agents2: ["Sova", "Killjoy", "Raze", "Astra", "Phoenix"],
      score: "11:13",
    },
    {
      player: "Asuna",
      date: "2021-05-01",
      tournament: "VCT 2021: North America Stage 2 Challengers Finals",
      map: "Ascent",
      kill: "22",
      death: "16",
      assist: "8",
      team1: "100 Thieves",
      team2: "Team Envy",
      agents1: ["Phoenix", "Sage", "Sova", "Omen", "Killjoy"],
      agents2: ["Sova", "Killjoy", "Raze", "Astra", "Phoenix"],
      score: "13:8",
    },
    {
      player: "Asuna",
      date: "2021-04-30",
      tournament: "VCT 2021: North America Stage 2 Challengers Finals",
      map: "Bind",
      kill: "27",
      death: "20",
      assist: "5",
      team1: "100 Thieves",
      team2: "Team Envy",
      agents1: ["Raze", "Sage", "Sova", "Omen", "Cypher"],
      agents2: ["Sova", "Viper", "Raze", "Astra", "Phoenix"],
      score: "11:13",
    },
    {
      player: "Asuna",
      date: "2021-04-30",
      tournament: "VCT 2021: North America Stage 2 Challengers Finals",
      map: "Bind",
      kill: "16",
      death: "16",
      assist: "3",
      team1: "100 Thieves",
      team2: "Sentinels",
      agents1: ["Raze", "Sage", "Sova", "Omen", "Cypher"],
      agents2: ["Viper", "Sova", "Raze", "Reyna", "Astra"],
      score: "4:13",
    },
    {
      player: "Asuna",
      date: "2021-04-30",
      tournament: "VCT 2021: North America Stage 2 Challengers Finals",
      map: "Icebox",
      kill: "10",
      death: "10",
      assist: "6",
      team1: "100 Thieves",
      team2: "Sentinels",
      agents1: ["Reyna", "Omen", "Sova", "Viper", "Killjoy"],
      agents2: ["Sova", "Jett", "Sage", "Reyna", "Viper"],
      score: "13:3",
    },
    {
      player: "Asuna",
      date: "2021-04-30",
      tournament: "VCT 2021: North America Stage 2 Challengers Finals",
      map: "Haven",
      kill: "24",
      death: "20",
      assist: "3",
      team1: "100 Thieves",
      team2: "Sentinels",
      agents1: ["Phoenix", "Skye", "Sova", "Omen", "Cypher"],
      agents2: ["Cypher", "Sova", "Phoenix", "Jett", "Astra"],
      score: "11:13",
    },
    {
      player: "Asuna",
      date: "2021-04-29",
      tournament: "VCT 2021: North America Stage 2 Challengers Finals",
      map: "Icebox",
      kill: "21",
      death: "18",
      assist: "6",
      team1: "100 Thieves",
      team2: "Andbox",
      agents1: ["Reyna", "Omen", "Sova", "Viper", "Killjoy"],
      agents2: ["Skye", "Raze", "Omen", "Viper", "Sage"],
      score: "13:10",
    },
    {
      player: "Asuna",
      date: "2021-04-29",
      tournament: "VCT 2021: North America Stage 2 Challengers Finals",
      map: "Ascent",
      kill: "22",
      death: "14",
      assist: "11",
      team1: "100 Thieves",
      team2: "Andbox",
      agents1: ["Phoenix", "Sage", "Sova", "Omen", "Killjoy"],
      agents2: ["Omen", "Phoenix", "Killjoy", "Sova", "Sage"],
      score: "13:9",
    },
    {
      player: "Asuna",
      date: "2021-04-11",
      tournament: "VCT 2021: North America Stage 2 Challengers 1",
      map: "Haven",
      kill: "17",
      death: "20",
      assist: "12",
      team1: "100 Thieves",
      team2: "XSET",
      agents1: ["Phoenix", "Sage", "Sova", "Omen", "Cypher"],
      agents2: ["Astra", "Sova", "Raze", "Cypher", "Phoenix"],
      score: "13:11",
    },
    {
      player: "Asuna",
      date: "2021-04-11",
      tournament: "VCT 2021: North America Stage 2 Challengers 1",
      map: "Split",
      kill: "16",
      death: "18",
      assist: "8",
      team1: "100 Thieves",
      team2: "XSET",
      agents1: ["Raze", "Sage", "Breach", "Jett", "Astra"],
      agents2: ["Astra", "Breach", "Raze", "Sage", "Viper"],
      score: "13:10",
    },
    {
      player: "Asuna",
      date: "2021-04-11",
      tournament: "VCT 2021: North America Stage 2 Challengers 1",
      map: "Ascent",
      kill: "21",
      death: "20",
      assist: "6",
      team1: "100 Thieves",
      team2: "XSET",
      agents1: ["Phoenix", "Sage", "Sova", "Omen", "Killjoy"],
      agents2: ["Astra", "Sova", "Raze", "Sage", "Viper"],
      score: "11:13",
    },
    {
      player: "Asuna",
      date: "2021-04-11",
      tournament: "VCT 2021: North America Stage 2 Challengers 1",
      map: "Icebox",
      kill: "20",
      death: "22",
      assist: "9",
      team1: "100 Thieves",
      team2: "XSET",
      agents1: ["Raze", "Sage", "Sova", "Omen", "Killjoy"],
      agents2: ["Astra", "Sova", "Raze", "Sage", "Viper"],
      score: "15:13",
    },
    {
      player: "Asuna",
      date: "2021-04-10",
      tournament: "VCT 2021: North America Stage 2 Challengers 1",
      map: "Haven",
      kill: "25",
      death: "12",
      assist: "5",
      team1: "100 Thieves",
      team2: "Team Envy",
      agents1: ["Phoenix", "Sage", "Sova", "Omen", "Cypher"],
      agents2: ["Sova", "Omen", "Raze", "Jett", "Breach"],
      score: "13:4",
    },
    {
      player: "Asuna",
      date: "2021-04-10",
      tournament: "VCT 2021: North America Stage 2 Challengers 1",
      map: "Ascent",
      kill: "32",
      death: "21",
      assist: "9",
      team1: "100 Thieves",
      team2: "Team Envy",
      agents1: ["Phoenix", "Sage", "Sova", "Omen", "Killjoy"],
      agents2: ["Sova", "Killjoy", "Raze", "Omen", "Skye"],
      score: "12:14",
    },
    {
      player: "Asuna",
      date: "2021-04-10",
      tournament: "VCT 2021: North America Stage 2 Challengers 1",
      map: "Bind",
      kill: "17",
      death: "12",
      assist: "3",
      team1: "100 Thieves",
      team2: "Team Envy",
      agents1: ["Raze", "Sage", "Sova", "Omen", "Cypher"],
      agents2: ["Sova", "Sage", "Raze", "Omen", "Skye"],
      score: "13:3",
    },
    {
      player: "Asuna",
      date: "2021-04-09",
      tournament: "VCT 2021: North America Stage 2 Challengers 1",
      map: "Ascent",
      kill: "11",
      death: "16",
      assist: "5",
      team1: "100 Thieves",
      team2: "Cloud9 Blue",
      agents1: ["Phoenix", "Sage", "Sova", "Omen", "Killjoy"],
      agents2: ["Raze", "Killjoy", "Jett", "Omen", "Sova"],
      score: "13:6",
    },
    {
      player: "Asuna",
      date: "2021-04-09",
      tournament: "VCT 2021: North America Stage 2 Challengers 1",
      map: "Icebox",
      kill: "26",
      death: "17",
      assist: "3",
      team1: "100 Thieves",
      team2: "Cloud9 Blue",
      agents1: ["Raze", "Sage", "Sova", "Omen", "Killjoy"],
      agents2: ["Raze", "Sage", "Jett", "Omen", "Sova"],
      score: "13:10",
    },
    {
      player: "Asuna",
      date: "2021-04-08",
      tournament: "VCT 2021: North America Stage 2 Challengers 1",
      map: "Bind",
      kill: "15",
      death: "17",
      assist: "2",
      team1: "100 Thieves",
      team2: "Andbox",
      agents1: ["Raze", "Sage", "Sova", "Omen", "Cypher"],
      agents2: ["Astra", "Raze", "Killjoy", "Breach", "Sova"],
      score: "13:9",
    },
    {
      player: "Asuna",
      date: "2021-04-08",
      tournament: "VCT 2021: North America Stage 2 Challengers 1",
      map: "Ascent",
      kill: "17",
      death: "13",
      assist: "5",
      team1: "100 Thieves",
      team2: "Andbox",
      agents1: ["Phoenix", "Sage", "Sova", "Omen", "Killjoy"],
      agents2: ["Sova", "Phoenix", "Omen", "Killjoy", "Sage"],
      score: "13:7",
    },
    {
      player: "Asuna",
      date: "2021-04-05",
      tournament: "VCT 2021: North America Stage 2 Challengers 1 - Qualifier",
      map: "Bind",
      kill: "14",
      death: "16",
      assist: "7",
      team1: "100 Thieves",
      team2: "rice and meatballs",
      agents1: ["Raze", "Sage", "Sova", "Omen", "Cypher"],
      agents2: ["Cypher", "Omen", "Jett", "Sova", "Reyna"],
      score: "13:8",
    },
    {
      player: "Asuna",
      date: "2021-04-05",
      tournament: "VCT 2021: North America Stage 2 Challengers 1 - Qualifier",
      map: "Icebox",
      kill: "23",
      death: "13",
      assist: "8",
      team1: "100 Thieves",
      team2: "rice and meatballs",
      agents1: ["Raze", "Sage", "Sova", "Omen", "Killjoy"],
      agents2: ["Killjoy", "Omen", "Jett", "Sova", "Sage"],
      score: "13:5",
    },
    {
      player: "Asuna",
      date: "2021-04-02",
      tournament: "VCT 2021: North America Stage 2 Challengers 1 - Qualifier",
      map: "Icebox",
      kill: "18",
      death: "6",
      assist: "2",
      team1: "100 Thieves",
      team2: "Time In",
      agents1: ["Raze", "Sage", "Sova", "Omen", "Killjoy"],
      agents2: ["Raze", "Sage", "Sova", "Killjoy", "Omen"],
      score: "13:1",
    },
    {
      player: "Asuna",
      date: "2021-04-02",
      tournament: "VCT 2021: North America Stage 2 Challengers 1 - Qualifier",
      map: "Ascent",
      kill: "19",
      death: "17",
      assist: "8",
      team1: "100 Thieves",
      team2: "Time In",
      agents1: ["Phoenix", "Sage", "Sova", "Omen", "Killjoy"],
      agents2: ["Breach", "Omen", "Sova", "Killjoy", "Jett"],
      score: "13:7",
    },
    {
      player: "Asuna",
      date: "2021-03-19",
      tournament: "VCT 2021: North America Stage 1 Masters",
      map: "Icebox",
      kill: "26",
      death: "20",
      assist: "7",
      team1: "100 Thieves",
      team2: "Gen.G Esports",
      agents1: ["Raze", "Omen", "Sova", "Sage", "Killjoy"],
      agents2: ["Omen", "Jett", "Killjoy", "Sova", "Sage"],
      score: "11:13",
    },
    {
      player: "Asuna",
      date: "2021-03-19",
      tournament: "VCT 2021: North America Stage 1 Masters",
      map: "Ascent",
      kill: "13",
      death: "17",
      assist: "5",
      team1: "100 Thieves",
      team2: "Gen.G Esports",
      agents1: ["Raze", "Omen", "Sova", "Sage", "Killjoy"],
      agents2: ["Omen", "Jett", "Killjoy", "Sova", "Reyna"],
      score: "6:13",
    },
    {
      player: "Asuna",
      date: "2021-03-14",
      tournament: "VCT 2021: North America Stage 1 Masters",
      map: "Haven",
      kill: "14",
      death: "24",
      assist: "8",
      team1: "100 Thieves",
      team2: "Sentinels",
      agents1: ["Raze", "Omen", "Sova", "Breach", "Cypher"],
      agents2: ["Cypher", "Sova", "Phoenix", "Jett", "Omen"],
      score: "14:16",
    },
    {
      player: "Asuna",
      date: "2021-03-14",
      tournament: "VCT 2021: North America Stage 1 Masters",
      map: "Ascent",
      kill: "10",
      death: "13",
      assist: "1",
      team1: "100 Thieves",
      team2: "Sentinels",
      agents1: ["Raze", "Omen", "Sova", "Sage", "Killjoy"],
      agents2: ["Cypher", "Sova", "Phoenix", "Jett", "Omen"],
      score: "2:13",
    },
    {
      player: "Asuna",
      date: "2021-03-13",
      tournament: "VCT 2021: North America Stage 1 Masters",
      map: "Haven",
      kill: "15",
      death: "16",
      assist: "7",
      team1: "100 Thieves",
      team2: "Immortals",
      agents1: ["Raze", "Omen", "Sova", "Breach", "Cypher"],
      agents2: ["Sova", "Omen", "Raze", "Killjoy", "Breach"],
      score: "13:8",
    },
    {
      player: "Asuna",
      date: "2021-03-13",
      tournament: "VCT 2021: North America Stage 1 Masters",
      map: "Ascent",
      kill: "15",
      death: "25",
      assist: "9",
      team1: "100 Thieves",
      team2: "Immortals",
      agents1: ["Raze", "Omen", "Sova", "Sage", "Killjoy"],
      agents2: ["Sova", "Omen", "Raze", "Killjoy", "Reyna"],
      score: "15:13",
    },
    {
      player: "Asuna",
      date: "2021-03-07",
      tournament: "VCT 2021: North America Stage 1 Challengers 3",
      map: "Icebox",
      kill: "8",
      death: "18",
      assist: "4",
      team1: "100 Thieves",
      team2: "FaZe Clan",
      agents1: ["Raze", "Omen", "Sova", "Sage", "Killjoy"],
      agents2: ["Jett", "Raze", "Sage", "Sova", "Omen"],
      score: "6:13",
    },
    {
      player: "Asuna",
      date: "2021-03-07",
      tournament: "VCT 2021: North America Stage 1 Challengers 3",
      map: "Bind",
      kill: "15",
      death: "18",
      assist: "5",
      team1: "100 Thieves",
      team2: "FaZe Clan",
      agents1: ["Raze", "Omen", "Sova", "Sage", "Cypher"],
      agents2: ["Jett", "Raze", "Omen", "Sova", "Breach"],
      score: "8:13",
    },
    {
      player: "Asuna",
      date: "2021-03-06",
      tournament: "VCT 2021: North America Stage 1 Challengers 3",
      map: "Icebox",
      kill: "25",
      death: "15",
      assist: "5",
      team1: "100 Thieves",
      team2: "Luminosity Gaming",
      agents1: ["Raze", "Omen", "Sova", "Sage", "Killjoy"],
      agents2: ["Killjoy", "Sova", "Sage", "Raze", "Omen"],
      score: "13:7",
    },
    {
      player: "Asuna",
      date: "2021-03-06",
      tournament: "VCT 2021: North America Stage 1 Challengers 3",
      map: "Ascent",
      kill: "20",
      death: "8",
      assist: "2",
      team1: "100 Thieves",
      team2: "Luminosity Gaming",
      agents1: ["Raze", "Omen", "Sova", "Sage", "Killjoy"],
      agents2: ["Cypher", "Sova", "Phoenix", "Reyna", "Omen"],
      score: "13:1",
    },
    {
      player: "Asuna",
      date: "2021-03-06",
      tournament: "VCT 2021: North America Stage 1 Challengers 3",
      map: "Ascent",
      kill: "30",
      death: "22",
      assist: "8",
      team1: "100 Thieves",
      team2: "Gen.G Esports",
      agents1: ["Raze", "Omen", "Sova", "Sage", "Killjoy"],
      agents2: ["Omen", "Jett", "Killjoy", "Sova", "Reyna"],
      score: "17:15",
    },
    {
      player: "Asuna",
      date: "2021-03-06",
      tournament: "VCT 2021: North America Stage 1 Challengers 3",
      map: "Haven",
      kill: "11",
      death: "17",
      assist: "4",
      team1: "100 Thieves",
      team2: "Gen.G Esports",
      agents1: ["Raze", "Omen", "Sova", "Breach", "Cypher"],
      agents2: ["Omen", "Jett", "Cypher", "Sova", "Phoenix"],
      score: "7:13",
    },
    {
      player: "Asuna",
      date: "2021-03-06",
      tournament: "VCT 2021: North America Stage 1 Challengers 3",
      map: "Bind",
      kill: "24",
      death: "10",
      assist: "7",
      team1: "100 Thieves",
      team2: "Gen.G Esports",
      agents1: ["Raze", "Omen", "Sova", "Sage", "Cypher"],
      agents2: ["Omen", "Jett", "Cypher", "Skye", "Raze"],
      score: "13:4",
    },
    {
      player: "Asuna",
      date: "2021-03-05",
      tournament: "VCT 2021: North America Stage 1 Challengers 3",
      map: "Icebox",
      kill: "20",
      death: "11",
      assist: "2",
      team1: "100 Thieves",
      team2: "TSM",
      agents1: ["Raze", "Omen", "Sova", "Sage", "Killjoy"],
      agents2: ["Raze", "Killjoy", "Sova", "Omen", "Jett"],
      score: "13:4",
    },
    {
      player: "Asuna",
      date: "2021-03-05",
      tournament: "VCT 2021: North America Stage 1 Challengers 3",
      map: "Ascent",
      kill: "19",
      death: "17",
      assist: "5",
      team1: "100 Thieves",
      team2: "TSM",
      agents1: ["Raze", "Omen", "Sova", "Sage", "Killjoy"],
      agents2: ["Phoenix", "Killjoy", "Sova", "Omen", "Jett"],
      score: "13:7",
    },
    {
      player: "Asuna",
      date: "2021-03-04",
      tournament: "VCT 2021: North America Stage 1 Challengers 3",
      map: "Haven",
      kill: "21",
      death: "17",
      assist: "8",
      team1: "100 Thieves",
      team2: "T1",
      agents1: ["Raze", "Omen", "Sova", "Breach", "Cypher"],
      agents2: ["Omen", "Cypher", "Sova", "Breach", "Jett"],
      score: "13:8",
    },
    {
      player: "Asuna",
      date: "2021-03-04",
      tournament: "VCT 2021: North America Stage 1 Challengers 3",
      map: "Icebox",
      kill: "4",
      death: "14",
      assist: "3",
      team1: "100 Thieves",
      team2: "T1",
      agents1: ["Raze", "Omen", "Sova", "Sage", "Killjoy"],
      agents2: ["Sage", "Viper", "Sova", "Raze", "Jett"],
      score: "1:13",
    },
    {
      player: "Asuna",
      date: "2021-03-04",
      tournament: "VCT 2021: North America Stage 1 Challengers 3",
      map: "Ascent",
      kill: "15",
      death: "13",
      assist: "6",
      team1: "100 Thieves",
      team2: "T1",
      agents1: ["Raze", "Omen", "Sova", "Sage", "Killjoy"],
      agents2: ["Omen", "Cypher", "Sova", "Breach", "Jett"],
      score: "13:8",
    },
    {
      player: "Asuna",
      date: "2021-03-04",
      tournament: "VCT 2021: North America Stage 1 Challengers 3",
      map: "Haven",
      kill: "21",
      death: "26",
      assist: "10",
      team1: "100 Thieves",
      team2: "NRG",
      agents1: ["Raze", "Omen", "Sova", "Breach", "Cypher"],
      agents2: ["Phoenix", "Cypher", "Sova", "Omen", "Jett"],
      score: "17:15",
    },
    {
      player: "Asuna",
      date: "2021-03-04",
      tournament: "VCT 2021: North America Stage 1 Challengers 3",
      map: "Bind",
      kill: "14",
      death: "18",
      assist: "4",
      team1: "100 Thieves",
      team2: "NRG",
      agents1: ["Raze", "Omen", "Sova", "Sage", "Cypher"],
      agents2: ["Phoenix", "Cypher", "Sova", "Omen", "Raze"],
      score: "7:13",
    },
    {
      player: "Asuna",
      date: "2021-03-04",
      tournament: "VCT 2021: North America Stage 1 Challengers 3",
      map: "Ascent",
      kill: "14",
      death: "16",
      assist: "2",
      team1: "100 Thieves",
      team2: "NRG",
      agents1: ["Raze", "Omen", "Sova", "Sage", "Killjoy"],
      agents2: ["Phoenix", "Cypher", "Sova", "Omen", "Jett"],
      score: "5:13",
    },
    {
      player: "Asuna",
      date: "2021-02-21",
      tournament: "VCT 2021: North America Stage 1 Challengers 2",
      map: "Ascent",
      kill: "12",
      death: "16",
      assist: "4",
      team1: "100 Thieves",
      team2: "Sentinels",
      agents1: ["Reyna", "Jett", "Sova", "Omen", "Killjoy"],
      agents2: ["Cypher", "Jett", "Phoenix", "Sova", "Omen"],
      score: "6:13",
    },
    {
      player: "Asuna",
      date: "2021-02-21",
      tournament: "VCT 2021: North America Stage 1 Challengers 2",
      map: "Haven",
      kill: "13",
      death: "16",
      assist: "3",
      team1: "100 Thieves",
      team2: "Sentinels",
      agents1: ["Phoenix", "Jett", "Sova", "Omen", "Cypher"],
      agents2: ["Cypher", "Jett", "Phoenix", "Sova", "Omen"],
      score: "4:13",
    },
    {
      player: "Asuna",
      date: "2021-02-20",
      tournament: "VCT 2021: North America Stage 1 Challengers 2",
      map: "Haven",
      kill: "19",
      death: "22",
      assist: "5",
      team1: "100 Thieves",
      team2: "Gen.G Esports",
      agents1: ["Phoenix", "Jett", "Sova", "Omen", "Cypher"],
      agents2: ["Omen", "Jett", "Cypher", "Sova", "Phoenix"],
      score: "15:13",
    },
    {
      player: "Asuna",
      date: "2021-02-20",
      tournament: "VCT 2021: North America Stage 1 Challengers 2",
      map: "Icebox",
      kill: "18",
      death: "8",
      assist: "16",
      team1: "100 Thieves",
      team2: "Gen.G Esports",
      agents1: ["Sage", "Jett", "Sova", "Omen", "Killjoy"],
      agents2: ["Omen", "Jett", "Cypher", "Sova", "Raze"],
      score: "13:4",
    },
    {
      player: "Asuna",
      date: "2021-02-20",
      tournament: "VCT 2021: North America Stage 1 Challengers 2",
      map: "Ascent",
      kill: "14",
      death: "14",
      assist: "3",
      team1: "100 Thieves",
      team2: "Luminosity Gaming",
      agents1: ["Reyna", "Jett", "Sova", "Omen", "Killjoy"],
      agents2: ["Cypher", "Sova", "Omen", "Reyna", "Raze"],
      score: "13:6",
    },
    {
      player: "Asuna",
      date: "2021-02-20",
      tournament: "VCT 2021: North America Stage 1 Challengers 2",
      map: "Icebox",
      kill: "10",
      death: "19",
      assist: "9",
      team1: "100 Thieves",
      team2: "Luminosity Gaming",
      agents1: ["Sage", "Jett", "Sova", "Omen", "Killjoy"],
      agents2: ["Raze", "Sova", "Sage", "Jett", "Omen"],
      score: "10:13",
    },
    {
      player: "Asuna",
      date: "2021-02-20",
      tournament: "VCT 2021: North America Stage 1 Challengers 2",
      map: "Bind",
      kill: "13",
      death: "18",
      assist: "4",
      team1: "100 Thieves",
      team2: "Luminosity Gaming",
      agents1: ["Raze", "Jett", "Sova", "Omen", "Cypher"],
      agents2: ["Cypher", "Sova", "Sage", "Raze", "Omen"],
      score: "7:13",
    },
    {
      player: "Asuna",
      date: "2021-02-14",
      tournament: "VCT 2021: North America Stage 1 Challengers 2 - Qualifier",
      map: "Icebox",
      kill: "20",
      death: "18",
      assist: "7",
      team1: "100 Thieves",
      team2: "Andbox",
      agents1: ["Reyna", "Jett", "Sova", "Omen", "Killjoy"],
      agents2: ["Raze", "Sage", "Sova", "Omen", "Jett"],
      score: "13:10",
    },
    {
      player: "Asuna",
      date: "2021-02-13",
      tournament: "VCT 2021: North America Stage 1 Challengers 2 - Qualifier",
      map: "Ascent",
      kill: "20",
      death: "9",
      assist: "10",
      team1: "100 Thieves",
      team2: "Andbox",
      agents1: ["Reyna", "Jett", "Sova", "Omen", "Killjoy"],
      agents2: ["Phoenix", "Sova", "Cypher", "Omen", "Jett"],
      score: "13:2",
    },
    {
      player: "Asuna",
      date: "2021-02-13",
      tournament: "VCT 2021: North America Stage 1 Challengers 2 - Qualifier",
      map: "Ascent",
      kill: "23",
      death: "10",
      assist: "6",
      team1: "100 Thieves",
      team2: "Ghost Gaming",
      agents1: ["Reyna", "Jett", "Sova", "Omen", "Killjoy"],
      agents2: ["Omen", "Phoenix", "Sova", "Raze", "Cypher"],
      score: "13:5",
    },
    {
      player: "Asuna",
      date: "2021-02-13",
      tournament: "VCT 2021: North America Stage 1 Challengers 2 - Qualifier",
      map: "Haven",
      kill: "22",
      death: "16",
      assist: "5",
      team1: "100 Thieves",
      team2: "Ghost Gaming",
      agents1: ["Phoenix", "Jett", "Sova", "Omen", "Cypher"],
      agents2: ["Omen", "Phoenix", "Sova", "Raze", "Cypher"],
      score: "13:10",
    },
    {
      player: "Asuna",
      date: "2021-02-13",
      tournament: "VCT 2021: North America Stage 1 Challengers 2 - Qualifier",
      map: "Ascent",
      kill: "17",
      death: "13",
      assist: "5",
      team1: "100 Thieves",
      team2: "NSIC",
      agents1: ["Reyna", "Jett", "Sova", "Omen", "Killjoy"],
      agents2: ["Killjoy", "Sova", "Reyna", "Jett", "Omen"],
      score: "13:4",
    },
    {
      player: "Asuna",
      date: "2021-02-12",
      tournament: "VCT 2021: North America Stage 1 Challengers 2 - Qualifier",
      map: "Haven",
      kill: "18",
      death: "15",
      assist: "7",
      team1: "100 Thieves",
      team2: "NSIC",
      agents1: ["Phoenix", "Jett", "Sova", "Omen", "Cypher"],
      agents2: ["Killjoy", "Sova", "Phoenix", "Jett", "Omen"],
      score: "13:8",
    },
    {
      player: "Asuna",
      date: "2021-01-29",
      tournament: "VCT 2021: North America Stage 1 Challengers 1 - Qualifier",
      map: "Haven",
      kill: "19",
      death: "22",
      assist: "10",
      team1: "100 Thieves",
      team2: "Carpe Noctem",
      agents1: ["Phoenix", "Jett", "Sova", "Omen", "Killjoy"],
      agents2: ["Omen", "Cypher", "Jett", "Sova", "Phoenix"],
      score: "11:13",
    },
    {
      player: "Asuna",
      date: "2021-01-29",
      tournament: "VCT 2021: North America Stage 1 Challengers 1 - Qualifier",
      map: "Bind",
      kill: "17",
      death: "21",
      assist: "10",
      team1: "100 Thieves",
      team2: "Carpe Noctem",
      agents1: ["Raze", "Sage", "Sova", "Omen", "Cypher"],
      agents2: ["Brimstone", "Cypher", "Raze", "Sova", "Phoenix"],
      score: "11:13",
    },
    {
      player: "Asuna",
      date: "2021-01-26",
      tournament: "Agent's Range - Agent's Rising #5",
      map: "Ascent",
      kill: "15",
      death: "17",
      assist: "2",
      team1: "Exception eSports",
      team2: "TBA",
      agents1: ["Jett", "Sova", "Omen", "Reyna", "Cypher"],
      agents2: ["Omen", "Killjoy", "Sova", "Breach", "Jett"],
      score: "9:13",
    },
  ],
};

function Player() {
  const { id } = useParams();
  return (
    <div className="player" style={{marginTop:"5vh"}}> 
      <div>Player : {id}</div>
      <Container>
        <Row>
          <Col lg="4">
            <CardPlayerDetail player={player} />
          </Col>
          <Col lg="8">
            <h4 style={{ color: "white" }}>Achievement</h4>
            <div
              style={{
                backgroundColor: "#212129",
                width: "60vw",
                height: "250px",
                overflow: "auto",
                overflowX: "hidden"
              }}
            >
                <Table
                  striped
                  bordered
                  hover
                  style={{
                    backgroundColor: "white",
                  }}
                >
                  <thead>
                    <tr>
                      <th>Date</th>
                      <th>Tournament</th>
                      <th>Map</th>
                      <th>K</th>
                      <th>D</th>
                      <th>A</th>
                      <th>Team</th>
                      <th>Score</th>
                      <th>vs. Team</th>
                    </tr>
                  </thead>

                  <tbody style={{ fontSize: "11px" }}>
                    {player.matches.map((match) => (
                      <tr>
                        <td>{match.date}</td>
                        <td>{match.tournament}</td>
                        <td>{match.map}</td>
                        <td>{match.kill}</td>
                        <td>{match.death}</td>
                        <td>{match.assist}</td>
                        <td>{match.team1}</td>
                        <td>{match.score}</td>
                        <td>{match.team2}</td>
                      </tr>
                    ))}
                  </tbody>
                </Table>
            </div>

            <h4 style={{ color: "white", marginTop: "10px" }}>Hardware</h4>
            <Card
              style={{
                backgroundColor: "#c4c4c4",
                borderRadius: "10px",
                width: "60vw",
              }}
            >
              <Container>
                <p style={{marginTop:"15px"}}>
                  <strong>Mouse : </strong>
                  {player.gamingGear.mouse.name}
                </p>
                <p>
                  <strong>Mousepad : </strong>
                  {player.gamingGear.mousepad.name}
                </p>
                <p>
                  <strong>Monitor : </strong>
                  {player.gamingGear.monitor.name}
                </p>
                <p>
                  <strong>Keyboard : </strong>
                  {player.gamingGear.keyboard.name}
                </p>
                <p>
                  <strong>Headset : </strong>
                  {player.gamingGear.headset.name}
                </p>
              </Container>
            </Card>
          </Col>
        </Row>
      </Container>
    </div>
  );
}

export default Player;
